db = [
  {
    "name": "Mario",
    "email": "mario@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 29,
    "address": "Rua ABC, 123",
    "other": "Gosta de livros",
    "interests": "Tecnologia",
    "feelings": "Motivado",
    "values": "Honestidade"
  },
  {
    "name": "João",
    "email": "joao@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 29,
    "address": "Rua das Flores, 123",
    "other": "Gosta de café",
    "interests": "Tecnologia",
    "feelings": "Motivado",
    "values": "Honestidade"
  },
  {
    "name": "Maria",
    "email": "maria@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 34,
    "address": "Av. Paulista, 987",
    "other": "Tem um gato",
    "interests": "Literatura",
    "feelings": "Tranquila",
    "values": "Respeito"
  },
  {
    "name": "Carlos",
    "email": "carlos@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 41,
    "address": "Rua A, 45",
    "other": "Corre maratonas",
    "interests": "Esportes",
    "feelings": "Energético",
    "values": "Determinação"
  },
  {
    "name": "Rafael",
    "email": "rafael@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 28,
    "address": "Rua do Comércio, 88",
    "other": "Viaja muito",
    "interests": "Fotografia",
    "feelings": "Reflexivo",
    "values": "Liberdade"
  },
  {
    "name": "Fernanda",
    "email": "fernanda@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 32,
    "address": "Travessa Central, 11",
    "other": "Vegetariana",
    "interests": "Culinária",
    "feelings": "Feliz",
    "values": "Saúde"
  },
  {
    "name": "Bruno",
    "email": "bruno@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 36,
    "address": "Rua Nova, 99",
    "other": "Toca violão",
    "interests": "Música",
    "feelings": "Calmo",
    "values": "Criatividade"
  },
  {
    "name": "Luciana",
    "email": "luciana@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 40,
    "address": "Alameda Verde, 27",
    "other": "Fala 3 idiomas",
    "interests": "Idiomas",
    "feelings": "Confiante",
    "values": "Conhecimento"
  },
  {
    "name": "Eduardo",
    "email": "eduardo@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 25,
    "address": "Rua Azul, 300",
    "other": "Ama filmes antigos",
    "interests": "Cinema",
    "feelings": "Curioso",
    "values": "Tradição"
  },
  {
    "name": "Paula",
    "email": "paula@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 37,
    "address": "Rua das Palmeiras, 50",
    "other": "Tem um blog",
    "interests": "Escrita",
    "feelings": "Criativa",
    "values": "Expressão"
  },
  {
    "name": "André",
    "email": "andre@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 30,
    "address": "Rua Oeste, 15",
    "other": "Surfista",
    "interests": "Natureza",
    "feelings": "Livre",
    "values": "Aventura"
  },
  {
    "name": "Camila",
    "email": "camila@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 31,
    "address": "Av. Central, 221",
    "other": "Trabalha com moda",
    "interests": "Design",
    "feelings": "Inspirada",
    "values": "Estilo"
  },
  {
    "name": "Thiago",
    "email": "thiago@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 38,
    "address": "Rua do Sol, 10",
    "other": "Pai de dois",
    "interests": "Família",
    "feelings": "Realizado",
    "values": "Compromisso"
  },
  {
    "name": "Juliana",
    "email": "juliana@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 27,
    "address": "Rua Leste, 3",
    "other": "Faz voluntariado",
    "interests": "Ação social",
    "feelings": "Solidária",
    "values": "Empatia"
  },
  {
    "name": "Fábio",
    "email": "fabio@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 44,
    "address": "Av. Sul, 77",
    "other": "Gosta de jardinagem",
    "interests": "Natureza",
    "feelings": "Paciente",
    "values": "Simplicidade"
  },
  {
    "name": "Tatiane",
    "email": "tatiane@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 35,
    "address": "Rua Bela Vista, 56",
    "other": "Tem uma startup",
    "interests": "Inovação",
    "feelings": "Ambiciosa",
    "values": "Progresso"
  },
  {
    "name": "Marcelo",
    "email": "marcelo@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 42,
    "address": "Rua Velha, 81",
    "other": "Faz podcasts",
    "interests": "Comunicação",
    "feelings": "Expressivo",
    "values": "Transparência"
  },
  {
    "name": "Vanessa",
    "email": "vanessa@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 33,
    "address": "Av. do Lago, 66",
    "other": "Faz yoga",
    "interests": "Bem-estar",
    "feelings": "Equilibrada",
    "values": "Harmonia"
  },
  {
    "name": "Igor",
    "email": "igor@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 39,
    "address": "Rua Industrial, 101",
    "other": "Coleciona vinis",
    "interests": "Música",
    "feelings": "Nostálgico",
    "values": "Autenticidade"
  },
  {
    "name": "Renata",
    "email": "renata@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 26,
    "address": "Rua do Parque, 5",
    "other": "Corre nas manhãs",
    "interests": "Saúde",
    "feelings": "Animada",
    "values": "Disciplina"
  },
  {
    "name": "Pedro",
    "email": "pedro@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 22,
    "address": "Rua das Rosas, 789",
    "other": "Joga futebol",
    "interests": "Games",
    "feelings": "Animado",
    "values": "Amizade"
  },
  {
    "name": "Alice",
    "email": "alice@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 50,
    "address": "Av. Brasil, 1000",
    "other": "Aprecia arte",
    "interests": "Arte",
    "feelings": "Contemplativa",
    "values": "Beleza"
  },
  {
    "name": "Gabriel",
    "email": "gabriel@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 33,
    "address": "Rua da Paz, 444",
    "other": "Programa computadores",
    "interests": "Programação",
    "feelings": "Focado",
    "values": "Eficiência"
  },
  {
    "name": "Laura",
    "email": "laura@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 24,
    "address": "Travessa das Estrelas, 20",
    "other": "Escreve poesia",
    "interests": "Poesia",
    "feelings": "Sensível",
    "values": "Originalidade"
  },
  {
    "name": "Daniel",
    "email": "daniel@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 45,
    "address": "Rua do Porto, 555",
    "other": "Navega em barcos",
    "interests": "Viagens",
    "feelings": "Aventureiro",
    "values": "Exploração"
  },
  {
    "name": "Sofia",
    "email": "sofia@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 21,
    "address": "Av. dos Coqueiros, 1",
    "other": "Canta em coral",
    "interests": "Canto",
    "feelings": "Jubilosa",
    "values": "Expressão"
  },
  {
    "name": "Lucas",
    "email": "lucas@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 29,
    "address": "Rua da Serra, 999",
    "other": "Faz trilhas",
    "interests": "Aventura",
    "feelings": "Vigoroso",
    "values": "Resiliência"
  },
  {
    "name": "Beatriz",
    "email": "beatriz@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 30,
    "address": "Praça Central, 7",
    "other": "Fotografa paisagens",
    "interests": "Natureza",
    "feelings": "Serena",
    "values": "Paz"
  },
  {
    "name": "Gustavo",
    "email": "gustavo@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 36,
    "address": "Rua da Inovação, 200",
    "other": "Investe no mercado",
    "interests": "Finanças",
    "feelings": "Estrategista",
    "values": "Prosperidade"
  },
  {
    "name": "Manuela",
    "email": "manuela@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 23,
    "address": "Alameda dos Anjos, 12",
    "other": "Desenha quadrinhos",
    "interests": "Ilustração",
    "feelings": "Imaginativa",
    "values": "Criatividade"
  },
  {
    "name": "Vitor",
    "email": "vitor@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 31,
    "address": "Rua do Progresso, 777",
    "other": "Aprendeu mandarim",
    "interests": "Idiomas",
    "feelings": "Curioso",
    "values": "Aprendizado"
  },
  {
    "name": "Isabela",
    "email": "isabela@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 38,
    "address": "Av. da Liberdade, 321",
    "other": "Faz cerâmica",
    "interests": "Artesanato",
    "feelings": "Tranquila",
    "values": "Paciência"
  },
  {
    "name": "Leo",
    "email": "leo@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 27,
    "address": "Rua do Saber, 101",
    "other": "Lê enciclopédias",
    "interests": "Conhecimento",
    "feelings": "Racional",
    "values": "Sabedoria"
  },
  {
    "name": "Clara",
    "email": "clara@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 40,
    "address": "Rua dos Sonhos, 80",
    "other": "Sonha alto",
    "interests": "Psicologia",
    "feelings": "Esperançosa",
    "values": "Realização"
  },
  {
    "name": "Felipe",
    "email": "felipe@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 26,
    "address": "Rua da Harmonia, 13",
    "other": "Pratica meditação",
    "interests": "Espiritualidade",
    "feelings": "Equilibrado",
    "values": "Paz Interior"
  },
  {
    "name": "Marina",
    "email": "marina@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 34,
    "address": "Av. da Criatividade, 42",
    "other": "Cria joias",
    "interests": "Joalheria",
    "feelings": "Inspirada",
    "values": "Beleza"
  },
  {
    "name": "Diego",
    "email": "diego@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 39,
    "address": "Rua dos Desafios, 22",
    "other": "Escala montanhas",
    "interests": "Esportes Radicais",
    "feelings": "Determinado",
    "values": "Superação"
  },
  {
    "name": "Helena",
    "email": "helena@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 28,
    "address": "Rua da Sustentabilidade, 111",
    "other": "Cultiva horta",
    "interests": "Meio Ambiente",
    "feelings": "Consciente",
    "values": "Sustentabilidade"
  },
  {
    "name": "Cauã",
    "email": "caua@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 25,
    "address": "Rua da Agilidade, 500",
    "other": "Joga basquete",
    "interests": "Esportes Coletivos",
    "feelings": "Competitivo",
    "values": "Trabalho em Equipe"
  },
  {
    "name": "Luiza",
    "email": "luiza@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 43,
    "address": "Av. da Gratidão, 90",
    "other": "Ajuda os outros",
    "interests": "Voluntariado",
    "feelings": "Grata",
    "values": "Generosidade"
  },
  {
    "name": "Giovanna",
    "email": "giovanna.souza@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 22,
    "address": "Alameda dos Ipês, 25",
    "other": "Estuda astrologia",
    "interests": "Esoterismo",
    "feelings": "Intuitiva",
    "values": "Mistério"
  },
  {
    "name": "Arthur",
    "email": "arthur.pereira@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 35,
    "address": "Rua do Cometa, 70",
    "other": "Observa estrelas",
    "interests": "Astronomia",
    "feelings": "Admirado",
    "values": "Curiosidade"
  },
  {
    "name": "Carla",
    "email": "carla.ribeiro@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 41,
    "address": "Praça do Sol Poente, 5",
    "other": "Pinta quadros",
    "interests": "Pintura",
    "feelings": "Expressiva",
    "values": "Estética"
  },
  {
    "name": "Ricardo",
    "email": "ricardo.martins@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 29,
    "address": "Rua do Futuro, 888",
    "other": "Desenvolve robôs",
    "interests": "Robótica",
    "feelings": "Inovador",
    "values": "Tecnologia"
  },
  {
    "name": "Patrícia",
    "email": "patricia.costa@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 33,
    "address": "Av. do Passado, 1950",
    "other": "Estuda história",
    "interests": "História",
    "feelings": "Reflexiva",
    "values": "Memória"
  },
  {
    "name": "Sergio",
    "email": "sergio.almeida@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 47,
    "address": "Rua da Sabedoria, 33",
    "other": "Ensina filosofia",
    "interests": "Filosofia",
    "feelings": "Pensativo",
    "values": "Razão"
  },
  {
    "name": "Viviane",
    "email": "viviane.gomes@gmail.com",
    "status": "Inativo",
    "pending": false,
    "age": 26,
    "address": "Rua do Coração, 77",
    "other": "Aconselha pessoas",
    "interests": "Psicologia",
    "feelings": "Empática",
    "values": "Compaixão"
  },
  {
    "name": "Fernando",
    "email": "fernando.lima@gmail.com",
    "status": "Ativo",
    "pending": false,
    "age": 32,
    "address": "Rua do Espírito, 9",
    "other": "Pratica ioga",
    "interests": "Bem-estar",
    "feelings": "Calmo",
    "values": "Serenidade"
  },
  {
    "name": "Monica",
    "email": "monica.ferreira@gmail.com",
    "status": "Inativo",
    "pending": true,
    "age": 37,
    "address": "Av. da Inspiração, 1010",
    "other": "Escreve roteiros",
    "interests": "Cinema",
    "feelings": "Visionária",
    "values": "Narrativa"
  },
  {
    "name": "Alexandre",
    "email": "alexandre@gmail.com",
    "status": "Ativo",
    "pending": true,
    "age": 48,
    "address": "Rua do Horizonte, 250",
    "other": "Gosta de pescar",
    "interests": "Pesca",
    "feelings": "Relaxado",
    "values": "Paciência"
  }
]

function createDB(token) {
  db.forEach(register => {
    fetch(`http://localhost:5204/api/registration/`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(register)
    })
  });
}